functionsDirectory = "/Users/yahyazobi/PETGO Finance /netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/yahyazobi/PETGO Finance "
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "/Users/yahyazobi/PETGO Finance /netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/"
to = "/PETGO Vantage v3.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]